### ISSUE TITLE
CargoProject::new panics when custom build.rs file is present

### ISSUE THREAD

**Issue by soltanmm** [koute/cargo-shim#3]
Repro (via `cargo-web`):
```
cargo new asdf
cd asdf
touch build.rs
cargo web build
```
It panics [here](https://github.com/koute/cargo-shim/blob/master/src/lib.rs#L78): `thread 'main' panicked at 'Unknown target kind: 'custom-build''`

**Comment by koute** [comment]
Fixed; thanks for the report! I'll publish new `cargo-web` with this correction soon.
